name: Deploy_Final-Project
services:
  backend:
    build:
      context: backend
      target: djangoDeploy
    ports:
      - 8000:8000
  frontend:
    build:
      context: frontend
      target: reactDeploy
    networks:
      - deploymentNetwork
    ports:
      - 3000:3000
    volumes: 
      - ./frontend/src:/code/src
