# Generated by Django 4.1.7 on 2023-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=1000, verbose_name='descr')),
                ('img', models.CharField(max_length=100, verbose_name='city')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
