# Generated by Django 4.1.7 on 2023-03-29 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.IntegerField(verbose_name='asiento')),
                ('graderia', models.CharField(max_length=100, verbose_name='graderia')),
                ('fila', models.IntegerField(verbose_name='fila')),
                ('precio', models.DecimalField(decimal_places=100, max_digits=100, verbose_name='precio')),
                ('disponible', models.BooleanField(verbose_name='disponible')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_partido', to='partidos.partidos')),
            ],
            options={
                'db_table': 'entradas',
            },
        ),
    ]
