# Generated by Django 4.1.7 on 2023-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('lat', models.CharField(max_length=50, verbose_name='lat')),
                ('long', models.CharField(max_length=50, verbose_name='long')),
                ('img', models.CharField(max_length=50, verbose_name='img')),
            ],
            options={
                'db_table': 'tienda',
            },
        ),
    ]
