# Generated by Django 4.1.7 on 2023-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competi', models.IntegerField(verbose_name='id_competi')),
                ('eq1', models.CharField(max_length=100, verbose_name='eq1')),
                ('eq2', models.CharField(max_length=100, verbose_name='eq2')),
                ('horario', models.DateTimeField(verbose_name='horario')),
                ('resultado', models.CharField(max_length=20, verbose_name='resultado')),
            ],
            options={
                'db_table': 'partidos',
            },
        ),
    ]
