# Generated by Django 4.1.7 on 2023-03-29 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50, verbose_name='correo')),
                ('name_complet', models.CharField(max_length=100, verbose_name='name_complet')),
                ('addres', models.CharField(max_length=100, verbose_name='addres')),
                ('num_telf', models.DecimalField(decimal_places=9, max_digits=9, verbose_name='num_telf')),
                ('avatar', models.CharField(max_length=50, verbose_name='avatar')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_socio', to='socios.socios')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
