--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2 (Debian 15.2-1.pgdg110+1)
-- Dumped by pg_dump version 15.2 (Debian 15.2-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO bioskin;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO bioskin;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO bioskin;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO bioskin;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO bioskin;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO bioskin;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: competiciones; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.competiciones (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    clasificacion integer NOT NULL
);


ALTER TABLE public.competiciones OWNER TO bioskin;

--
-- Name: competiciones_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.competiciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.competiciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO bioskin;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO bioskin;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO bioskin;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO bioskin;

--
-- Name: entrada_reserved; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.entrada_reserved (
    id bigint NOT NULL,
    entrada_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.entrada_reserved OWNER TO bioskin;

--
-- Name: entrada_reserved_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.entrada_reserved ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entrada_reserved_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: entradas; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.entradas (
    id bigint NOT NULL,
    asiento integer NOT NULL,
    graderia character varying(100) NOT NULL,
    fila integer NOT NULL,
    precio numeric(100,100) NOT NULL,
    disponible boolean NOT NULL,
    partido_id bigint NOT NULL
);


ALTER TABLE public.entradas OWNER TO bioskin;

--
-- Name: entradas_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.entradas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entradas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipo; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.equipo (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    city character varying(100) NOT NULL,
    stadium character varying(100) NOT NULL,
    shield character varying(500) NOT NULL,
    lat numeric(15,10) NOT NULL,
    long numeric(15,10) NOT NULL
);


ALTER TABLE public.equipo OWNER TO bioskin;

--
-- Name: equipo_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.equipo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: integrantes; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.integrantes (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    apellidos character varying(50) NOT NULL,
    nacionalidad character varying(50) NOT NULL,
    fech_naci date NOT NULL,
    avatar character varying(100) NOT NULL,
    player_id bigint NOT NULL,
    tecnico_id bigint NOT NULL
);


ALTER TABLE public.integrantes OWNER TO bioskin;

--
-- Name: integrantes_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.integrantes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.integrantes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jugadores; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.jugadores (
    id bigint NOT NULL,
    dorsal integer NOT NULL,
    goles integer NOT NULL,
    tarjetas_amar integer NOT NULL,
    tarjetas_roj integer NOT NULL,
    lesionado boolean NOT NULL
);


ALTER TABLE public.jugadores OWNER TO bioskin;

--
-- Name: jugadores_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.jugadores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jugadores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.news (
    id bigint NOT NULL,
    descr character varying(1000) NOT NULL,
    img character varying(100) NOT NULL
);


ALTER TABLE public.news OWNER TO bioskin;

--
-- Name: news_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partidos; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.partidos (
    id bigint NOT NULL,
    competi integer NOT NULL,
    eq1 character varying(100) NOT NULL,
    eq2 character varying(100) NOT NULL,
    horario timestamp with time zone NOT NULL,
    resultado character varying(20) NOT NULL
);


ALTER TABLE public.partidos OWNER TO bioskin;

--
-- Name: partidos_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.partidos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.productos (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    type character varying(100) NOT NULL,
    talla character varying(50) NOT NULL,
    img character varying(50) NOT NULL
);


ALTER TABLE public.productos OWNER TO bioskin;

--
-- Name: productos_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profile; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.profile (
    id bigint NOT NULL,
    correo character varying(50) NOT NULL,
    name_complet character varying(100) NOT NULL,
    addres character varying(100) NOT NULL,
    num_telf integer NOT NULL,
    avatar character varying(50) NOT NULL,
    type character varying(50) NOT NULL,
    socio_id bigint NOT NULL
);


ALTER TABLE public.profile OWNER TO bioskin;

--
-- Name: profile_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socios; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.socios (
    id bigint NOT NULL,
    num_socio integer NOT NULL
);


ALTER TABLE public.socios OWNER TO bioskin;

--
-- Name: socios_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.socios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tecnicos; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.tecnicos (
    id bigint NOT NULL,
    type character varying(20) NOT NULL
);


ALTER TABLE public.tecnicos OWNER TO bioskin;

--
-- Name: tecnicos_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.tecnicos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tecnicos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.tienda (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    lat character varying(50) NOT NULL,
    long character varying(50) NOT NULL,
    img character varying(50) NOT NULL
);


ALTER TABLE public.tienda OWNER TO bioskin;

--
-- Name: tienda_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.tienda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: bioskin
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    username character varying(50) NOT NULL,
    passwd character varying(50) NOT NULL,
    profile_id bigint NOT NULL
);


ALTER TABLE public.users OWNER TO bioskin;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: bioskin
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1       Can add log entry       1       add_logentry
2       Can change log entry    1       change_logentry
3       Can delete log entry    1       delete_logentry
4       Can view log entry      1       view_logentry
5       Can add equipo  2       add_equipo
6       Can change equipo       2       change_equipo
7       Can delete equipo       2       delete_equipo
8       Can view equipo 2       view_equipo
9       Can add competiciones   3       add_competiciones
10      Can change competiciones        3       change_competiciones
11      Can delete competiciones        3       delete_competiciones
12      Can view competiciones  3       view_competiciones
13      Can add entrada_reserved        4       add_entrada_reserved
14      Can change entrada_reserved     4       change_entrada_reserved
15      Can delete entrada_reserved     4       delete_entrada_reserved
16      Can view entrada_reserved       4       view_entrada_reserved
17      Can add entrada 5       add_entrada
18      Can change entrada      5       change_entrada
19      Can delete entrada      5       delete_entrada
20      Can view entrada        5       view_entrada
21      Can add integrantes     6       add_integrantes
22      Can change integrantes  6       change_integrantes
23      Can delete integrantes  6       delete_integrantes
24      Can view integrantes    6       view_integrantes
25      Can add jugadores       7       add_jugadores
26      Can change jugadores    7       change_jugadores
27      Can delete jugadores    7       delete_jugadores
28      Can view jugadores      7       view_jugadores
29      Can add news    8       add_news
30      Can change news 8       change_news
31      Can delete news 8       delete_news
32      Can view news   8       view_news
33      Can add partidos        9       add_partidos
34      Can change partidos     9       change_partidos
35      Can delete partidos     9       delete_partidos
36      Can view partidos       9       view_partidos
37      Can add productos       10      add_productos
38      Can change productos    10      change_productos
39      Can delete productos    10      delete_productos
40      Can view productos      10      view_productos
41      Can add socios  11      add_socios
42      Can change socios       11      change_socios
43      Can delete socios       11      delete_socios
44      Can view socios 11      view_socios
45      Can add tecnicos        12      add_tecnicos
46      Can change tecnicos     12      change_tecnicos
47      Can delete tecnicos     12      delete_tecnicos
48      Can view tecnicos       12      view_tecnicos
49      Can add tienda  13      add_tienda
50      Can change tienda       13      change_tienda
51      Can delete tienda       13      delete_tienda
52      Can view tienda 13      view_tienda
53      Can add users   14      add_users
54      Can change users        14      change_users
55      Can delete users        14      delete_users
56      Can view users  14      view_users
57      Can add profile 15      add_profile
58      Can change profile      15      change_profile
59      Can delete profile      15      delete_profile
60      Can view profile        15      view_profile
61      Can add permission      16      add_permission
62      Can change permission   16      change_permission
63      Can delete permission   16      delete_permission
64      Can view permission     16      view_permission
65      Can add group   17      add_group
66      Can change group        17      change_group
67      Can delete group        17      delete_group
68      Can view group  17      view_group
69      Can add user    18      add_user
70      Can change user 18      change_user
71      Can delete user 18      delete_user
72      Can view user   18      view_user
73      Can add content type    19      add_contenttype
74      Can change content type 19      change_contenttype
75      Can delete content type 19      delete_contenttype
76      Can view content type   19      view_contenttype
77      Can add session 20      add_session
78      Can change session      20      change_session
79      Can delete session      20      delete_session
80      Can view session        20      view_session
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: competiciones; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.competiciones (id, name, clasificacion) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1       admin   logentry
2       equipo  equipo
3       competiciones   competiciones
4       entrada_reserved        entrada_reserved
5       entradas        entrada
6       integrantes     integrantes
7       jugadores       jugadores
8       news    news
9       partidos        partidos
10      productos       productos
11      socios  socios
12      tecnicos        tecnicos
13      tienda  tienda
14      users   users
15      profile profile
16      auth    permission
17      auth    group
18      auth    user
19      contenttypes    contenttype
20      sessions        session
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1       contenttypes    0001_initial    2023-03-29 17:00:22.009957+00
2       auth    0001_initial    2023-03-29 17:00:22.09681+00
3       admin   0001_initial    2023-03-29 17:00:22.121311+00
4       admin   0002_logentry_remove_auto_add   2023-03-29 17:00:22.129819+00
5       admin   0003_logentry_add_action_flag_choices   2023-03-29 17:00:22.139787+00
6       contenttypes    0002_remove_content_type_name   2023-03-29 17:00:22.157861+00
7       auth    0002_alter_permission_name_max_length   2023-03-29 17:00:22.167919+00
8       auth    0003_alter_user_email_max_length        2023-03-29 17:00:22.177461+00
9       auth    0004_alter_user_username_opts   2023-03-29 17:00:22.18594+00
10      auth    0005_alter_user_last_login_null 2023-03-29 17:00:22.197481+00
11      auth    0006_require_contenttypes_0002  2023-03-29 17:00:22.201452+00
12      auth    0007_alter_validators_add_error_messages        2023-03-29 17:00:22.211416+00
13      auth    0008_alter_user_username_max_length     2023-03-29 17:00:22.224937+00
14      auth    0009_alter_user_last_name_max_length    2023-03-29 17:00:22.233908+00
15      auth    0010_alter_group_name_max_length        2023-03-29 17:00:22.244477+00
16      auth    0011_update_proxy_permissions   2023-03-29 17:00:22.254693+00
17      auth    0012_alter_user_first_name_max_length   2023-03-29 17:00:22.265765+00
18      competiciones   0001_initial    2023-03-29 17:00:22.27479+00
19      socios  0001_initial    2023-03-29 17:00:22.283788+00
20      profile 0001_initial    2023-03-29 17:00:22.300862+00
21      users   0001_initial    2023-03-29 17:00:22.315704+00
22      partidos        0001_initial    2023-03-29 17:00:22.325728+00
23      entradas        0001_initial    2023-03-29 17:00:22.341784+00
24      entrada_reserved        0001_initial    2023-03-29 17:00:22.363814+00
25      equipo  0001_initial    2023-03-29 17:00:22.375904+00
26      tecnicos        0001_initial    2023-03-29 17:00:22.384876+00
27      jugadores       0001_initial    2023-03-29 17:00:22.395198+00
28      integrantes     0001_initial    2023-03-29 17:00:22.415803+00
29      news    0001_initial    2023-03-29 17:00:22.425741+00
30      productos       0001_initial    2023-03-29 17:00:22.435835+00
31      sessions        0001_initial    2023-03-29 17:00:22.453879+00
32      tienda  0001_initial    2023-03-29 17:00:22.462885+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: entrada_reserved; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.entrada_reserved (id, entrada_id, user_id) FROM stdin;
\.


--
-- Data for Name: entradas; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.entradas (id, asiento, graderia, fila, precio, disponible, partido_id) FROM stdin;
\.


--
-- Data for Name: equipo; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.equipo (id, name, city, stadium, shield, lat, long) FROM stdin;
\.


--
-- Data for Name: integrantes; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.integrantes (id, name, apellidos, nacionalidad, fech_naci, avatar, player_id, tecnico_id) FROM stdin;
\.


--
-- Data for Name: jugadores; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.jugadores (id, dorsal, goles, tarjetas_amar, tarjetas_roj, lesionado) FROM stdin;
\.


--
-- Data for Name: news; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.news (id, descr, img) FROM stdin;
\.


--
-- Data for Name: partidos; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.partidos (id, competi, eq1, eq2, horario, resultado) FROM stdin;
\.


--
-- Data for Name: productos; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.productos (id, name, type, talla, img) FROM stdin;
\.


--
-- Data for Name: profile; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.profile (id, correo, name_complet, addres, num_telf, avatar, type, socio_id) FROM stdin;
1       prueba@gmail.com        Sergi Biosca Beneyto    C/Alacant       12      prueba.jpg      eeee    1
\.


--
-- Data for Name: socios; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.socios (id, num_socio) FROM stdin;
1       289
\.


--
-- Data for Name: tecnicos; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.tecnicos (id, type) FROM stdin;
\.


--
-- Data for Name: tienda; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.tienda (id, name, lat, long, img) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: bioskin
--

COPY public.users (id, username, passwd, profile_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 80, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: competiciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.competiciones_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 20, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 32, true);


--
-- Name: entrada_reserved_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.entrada_reserved_id_seq', 1, false);


--
-- Name: entradas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.entradas_id_seq', 1, false);


--
-- Name: equipo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.equipo_id_seq', 1, false);


--
-- Name: integrantes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.integrantes_id_seq', 1, false);


--
-- Name: jugadores_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.jugadores_id_seq', 1, false);


--
-- Name: news_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.news_id_seq', 1, false);


--
-- Name: partidos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.partidos_id_seq', 1, false);


--
-- Name: productos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.productos_id_seq', 1, false);


--
-- Name: profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.profile_id_seq', 1, false);


--
-- Name: socios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.socios_id_seq', 1, false);


--
-- Name: tecnicos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.tecnicos_id_seq', 1, false);


--
-- Name: tienda_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.tienda_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bioskin
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: competiciones competiciones_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.competiciones
    ADD CONSTRAINT competiciones_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: entrada_reserved entrada_reserved_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.entrada_reserved
    ADD CONSTRAINT entrada_reserved_pkey PRIMARY KEY (id);


--
-- Name: entradas entradas_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.entradas
    ADD CONSTRAINT entradas_pkey PRIMARY KEY (id);


--
-- Name: equipo equipo_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.equipo
    ADD CONSTRAINT equipo_pkey PRIMARY KEY (id);


--
-- Name: integrantes integrantes_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.integrantes
    ADD CONSTRAINT integrantes_pkey PRIMARY KEY (id);


--
-- Name: jugadores jugadores_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.jugadores
    ADD CONSTRAINT jugadores_pkey PRIMARY KEY (id);


--
-- Name: news news_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_pkey PRIMARY KEY (id);


--
-- Name: partidos partidos_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.partidos
    ADD CONSTRAINT partidos_pkey PRIMARY KEY (id);


--
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- Name: profile profile_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_pkey PRIMARY KEY (id);


--
-- Name: socios socios_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.socios
    ADD CONSTRAINT socios_pkey PRIMARY KEY (id);


--
-- Name: tecnicos tecnicos_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.tecnicos
    ADD CONSTRAINT tecnicos_pkey PRIMARY KEY (id);


--
-- Name: tienda tienda_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.tienda
    ADD CONSTRAINT tienda_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);

--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: entrada_reserved_entrada_id_484f7015; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX entrada_reserved_entrada_id_484f7015 ON public.entrada_reserved USING btree (entrada_id);


--
-- Name: entrada_reserved_user_id_ce8e1e85; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX entrada_reserved_user_id_ce8e1e85 ON public.entrada_reserved USING btree (user_id);


--
-- Name: entradas_partido_id_61b43b86; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX entradas_partido_id_61b43b86 ON public.entradas USING btree (partido_id);


--
-- Name: integrantes_player_id_6bdf05c6; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX integrantes_player_id_6bdf05c6 ON public.integrantes USING btree (player_id);


--
-- Name: integrantes_tecnico_id_c979d7d9; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX integrantes_tecnico_id_c979d7d9 ON public.integrantes USING btree (tecnico_id);


--
-- Name: profile_socio_id_297960bb; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX profile_socio_id_297960bb ON public.profile USING btree (socio_id);


--
-- Name: users_profile_id_d5052114; Type: INDEX; Schema: public; Owner: bioskin
--

CREATE INDEX users_profile_id_d5052114 ON public.users USING btree (profile_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: entrada_reserved entrada_reserved_entrada_id_484f7015_fk_entradas_id; Type: FK CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.entrada_reserved
    ADD CONSTRAINT entrada_reserved_entrada_id_484f7015_fk_entradas_id FOREIGN KEY (entrada_id) REFERENCES public.entradas(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: entrada_reserved entrada_reserved_user_id_ce8e1e85_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.entrada_reserved
    ADD CONSTRAINT entrada_reserved_user_id_ce8e1e85_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: entradas entradas_partido_id_61b43b86_fk_partidos_id; Type: FK CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.entradas
    ADD CONSTRAINT entradas_partido_id_61b43b86_fk_partidos_id FOREIGN KEY (partido_id) REFERENCES public.partidos(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: integrantes integrantes_player_id_6bdf05c6_fk_jugadores_id; Type: FK CONSTRAINT; Schema: public; Owner: bioskin--

ALTER TABLE ONLY public.integrantes
    ADD CONSTRAINT integrantes_player_id_6bdf05c6_fk_jugadores_id FOREIGN KEY (player_id) REFERENCES public.jugadores(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: integrantes integrantes_tecnico_id_c979d7d9_fk_tecnicos_id; Type: FK CONSTRAINT; Schema: public; Owner: bioskin--

ALTER TABLE ONLY public.integrantes
    ADD CONSTRAINT integrantes_tecnico_id_c979d7d9_fk_tecnicos_id FOREIGN KEY (tecnico_id) REFERENCES public.tecnicos(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: profile profile_socio_id_297960bb_fk_socios_id; Type: FK CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_socio_id_297960bb_fk_socios_id FOREIGN KEY (socio_id) REFERENCES public.socios(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_profile_id_d5052114_fk_profile_id; Type: FK CONSTRAINT; Schema: public; Owner: bioskin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_profile_id_d5052114_fk_profile_id FOREIGN KEY (profile_id) REFERENCES public.profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--
