# Generated by Django 4.1.7 on 2023-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorsal', models.IntegerField(verbose_name='dorsal')),
                ('goles', models.IntegerField(verbose_name='goles')),
                ('tarjetas_amar', models.IntegerField(verbose_name='tarjetas_amar')),
                ('tarjetas_roj', models.IntegerField(verbose_name='tarjetas_roj')),
                ('lesionado', models.BooleanField(verbose_name='lesionado')),
            ],
            options={
                'db_table': 'jugadores',
            },
        ),
    ]
